version: '3.4'
services:
  redis:
    image: redis:3.2.7

  postgres:
    image: postgres:11
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow

  webserver:
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
        - postgres
    environment:
        - LOAD_EX=n
        - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    env_file:
        - ../local.env
    volumes:
        - ../${DAG_DIR}:/usr/local/airflow/dags/${DAG_DIR}
        - ./data:/usr/local/airflow/data
        - ./docker-requirements.txt:/requirements.txt
    ports:
        - "8010:8080"
    command: webserver
    healthcheck:
        test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
        interval: 30s
        timeout: 30s
        retries: 3

  flower:
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
        - redis
        - webserver
    environment:
        - LOAD_EX=n
        - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    ports:
        - "5555:5555"
    command: flower
    volumes:
        - ./docker-requirements.txt:/requirements.txt

  scheduler:
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
        - webserver
    volumes:
        - ../${DAG_DIR}:/usr/local/airflow/dags/${DAG_DIR}
        - ./data:/usr/local/airflow/data
        - ./docker-requirements.txt:/requirements.txt
    env_file:
        - ../local.env
    environment:
        - LOAD_EX=n
        - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    command: scheduler

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    restart: always
    depends_on:
        - scheduler
    volumes:
        - ../${DAG_DIR}:/usr/local/airflow/dags/${DAG_DIR}
        - ./data:/usr/local/airflow/data
        - ./docker-requirements.txt:/requirements.txt
    env_file:
        - ../local.env
    environment:
        - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    command: worker
