services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:14
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow

  webserver:
    image: apache/airflow:2.8.1-python3.9
    restart: always
    depends_on:
        - postgres
    environment:
        - AIRFLOW__CORE__LOAD_EXAMPLES=False
        - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
        - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/1
        - AIRFLOW__WEBSERVER__SECRET_KEY=Ud+K7/gXg+IWP5F9HjsqXw==
        - LOAD_EX=n
    env_file:
        - ../local.env
    volumes:
        - ../${DAG_DIR}/${DAG_DIR}:/opt/airflow/dags/${DAG_DIR}
        - ./data:/opt/airflow/data
        - ./docker-requirements.txt:/requirements.txt
        - ./bin/start.sh:/usr/bin/start.sh

    ports:
        - "8010:8080"

    entrypoint: /usr/bin/start.sh
    healthcheck:
        test: ["CMD-SHELL", "[ -f /opt/airflow/airflow-webserver.pid ]"]
        interval: 10s
        timeout: 20s
        retries: 3

  flower:
    image: apache/airflow:2.8.1-python3.9
    restart: always
    depends_on:
        - redis
        - webserver
    environment:
        - AIRFLOW__CORE__LOAD_EXAMPLES=False
        - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/1
        - AIRFLOW__WEBSERVER__SECRET_KEY=Ud+K7/gXg+IWP5F9HjsqXw==
        - LOAD_EX=n
    ports:
        - "5555:5555"
    command: celery flower
    volumes:
        - ./docker-requirements.txt:/requirements.txt

  scheduler:
    image: apache/airflow:2.8.1-python3.9
    restart: always
    depends_on:
        - webserver
    volumes:
        - ../${DAG_DIR}/${DAG_DIR}:/opt/airflow/dags/${DAG_DIR}
        - ./data:/opt/airflow/data
        - ./docker-requirements.txt:/requirements.txt
    env_file:
        - ../local.env
    environment:
        - AIRFLOW__CORE__LOAD_EXAMPLES=False
        - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/1
        - AIRFLOW__WEBSERVER__SECRET_KEY=Ud+K7/gXg+IWP5F9HjsqXw==
        - LOAD_EX=n
    command: scheduler

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    restart: always
    depends_on:
        - scheduler
    volumes:
        - ../${DAG_DIR}/${DAG_DIR}:/opt/airflow/dags/${DAG_DIR}
        - ./data:/opt/airflow/data
        - ./docker-requirements.txt:/requirements.txt
        - ./worker/.bashrc:/opt/airflow/.bashrc
    env_file:
        - ../local.env
    environment:
        - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
        - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
        - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/1
        - AIRFLOW__WEBSERVER__SECRET_KEY=Ud+K7/gXg+IWP5F9HjsqXw==
        - LOAD_EX=n
    command: celery worker
